#!/usr/bin/env bash
# Refresh the Cloudflare source ranges used by the origin lockdown (nftables
# sets) and by nginx real-IP restoration.
#
# Fails CLOSED onto the previous ranges: if the fetch looks implausible we
# exit non-zero without touching live config. An empty set would drop
# Cloudflare itself and take the panel offline; stale ranges are always the
# safer state.
set -euo pipefail

V4_URL="https://www.cloudflare.com/ips-v4"
V6_URL="https://www.cloudflare.com/ips-v6"
MIN_CIDRS=5
NFT_TABLE="inet jamasp_edge"
NGINX_SNIPPET="/etc/nginx/conf.d/cloudflare-real-ip.conf"

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

curl -fsS --max-time 20 "$V4_URL" -o "$tmp/v4"
curl -fsS --max-time 20 "$V6_URL" -o "$tmp/v6"

# Keep only well-formed CIDRs — guards against error pages and truncation.
grep -Ex '[0-9.]+/[0-9]+'       "$tmp/v4" > "$tmp/v4.clean" || true
grep -Ex '[0-9a-fA-F:]+/[0-9]+' "$tmp/v6" > "$tmp/v6.clean" || true

v4n="$(wc -l < "$tmp/v4.clean")"
v6n="$(wc -l < "$tmp/v6.clean")"
if [ "$v4n" -lt "$MIN_CIDRS" ] || [ "$v6n" -lt "$MIN_CIDRS" ]; then
    echo "refresh-cf-ranges: implausible list (v4=$v4n v6=$v6n) — keeping existing ranges" >&2
    exit 1
fi

# nftables: replace both sets in one atomic transaction.
{
    echo "flush set $NFT_TABLE cf_v4"
    echo "flush set $NFT_TABLE cf_v6"
    echo "add element $NFT_TABLE cf_v4 { $(paste -sd, "$tmp/v4.clean") }"
    echo "add element $NFT_TABLE cf_v6 { $(paste -sd, "$tmp/v6.clean") }"
} > "$tmp/sets.nft"
nft -f "$tmp/sets.nft"

# nginx real-IP snippet — only once nginx is actually installed.
if command -v nginx >/dev/null 2>&1 && [ -d /etc/nginx/conf.d ]; then
    {
        echo "# Generated by refresh-cf-ranges.sh — do not edit by hand."
        sed 's|^|set_real_ip_from |; s|$|;|' "$tmp/v4.clean"
        sed 's|^|set_real_ip_from |; s|$|;|' "$tmp/v6.clean"
        echo "real_ip_header CF-Connecting-IP;"
        echo "real_ip_recursive on;"
    } > "$tmp/real-ip.conf"

    if ! cmp -s "$tmp/real-ip.conf" "$NGINX_SNIPPET"; then
        install -m 0644 "$tmp/real-ip.conf" "$NGINX_SNIPPET"
        nginx -t && systemctl reload nginx
    fi
fi

echo "refresh-cf-ranges: ok (v4=$v4n v6=$v6n)"
